class AppModule:
	processID: int
	appName: str

	def __init__(self, processID: int, appName: str | None = None) -> None: ...
	def terminate(self) -> None: ...

def registerExecutableWithAppModule(executableName: str, appModName: str) -> None: ...
def unregisterExecutable(executableName: str) -> None: ...
