from typing import Self

class TextInfo:
	@property
	def obj(self) -> object: ...
	@property
	def text(self) -> str: ...
	def copy(self) -> Self: ...
	def collapse(self, end: bool = False) -> None: ...
	def compareEndPoints(self, other: Self, which: str) -> int: ...
	def setEndPoint(self, other: Self, which: str) -> None: ...
	def expand(self, unit: str) -> None: ...
